Repository ferncabrera/open_ims, pull requests merged in 2023-07, with the labels that each got.

#9 Adding logging to our server
  server/index.ts
  server/package-lock.json
  server/package.json
Labels: enhancement

#11 Docker +Skaffold + K8s configuration
  client/Dockerfile.dev
  client/src/App.tsx
  client/src/utilities/apiHelpers.ts
  client/vite.config.ts
  k8s/client-cluster-ip-service.yaml
  k8s/client-deployment.yaml
  k8s/ingress-service.yaml
  k8s/server-cluster-ip-service.yaml
  k8s/server-deployment.yaml
  server/Dockerfile.dev
  server/index.ts
  skaffold.yaml
Labels: critical

#12 Update README.md
  README.md
Labels: documentation

#14 testing beep fixing docker
  client/src/App.tsx
  server/Dockerfile.dev
Labels: bug

#29 Misc changes for CI/CD
  .gitignore
  common/database/kustomize/base/ingress-service.yaml
  common/database/kustomize/base/kustomization.yaml
  common/database/kustomize/overlays/dev/kustomization.yaml
  common/database/kustomize/overlays/prod/kustomization.yaml
  common/database/kustomize/overlays/staging/kustomization.yaml
  common/ingress/kustomize/base/ingress-service.yaml
  common/ingress/kustomize/base/kustomization.yaml
  common/ingress/kustomize/overlays/dev/kustomization.yaml
  common/ingress/kustomize/overlays/prod/kustomization.yaml
  common/ingress/kustomize/overlays/staging/kustomization.yaml
  microservices/client/src/App.css
  microservices/client/src/containers/ServerPing.tsx
  microservices/client/src/main.tsx
  microservices/client/src/routes.tsx
  skaffold.yaml
Labels: enhancement

#39 Postgresql instances are running in all envs on start
  common/database/README.md
  common/database/kustomize/base/ingress-service.yaml
  common/database/kustomize/base/kustomization.yaml
  common/database/kustomize/base/postgres-headless-port-service.yaml
  common/database/kustomize/base/postgres-persistent-volume-claim.yaml
  common/database/kustomize/base/postgres-pod.yaml
  common/database/kustomize/base/postgres-stateful-set.yaml
  common/database/kustomize/overlays/dev/config.properties
  common/database/kustomize/overlays/dev/kustomization.yaml
  common/database/kustomize/overlays/prod/config.properties
  common/database/kustomize/overlays/prod/kustomization.yaml
  common/database/kustomize/overlays/staging/config.properties
  common/database/kustomize/overlays/staging/init-container-patch.json
  common/database/kustomize/overlays/staging/kustomization.yaml
  common/ingress/kustomize/base/ingress-service.yaml
  common/ingress/kustomize/overlays/dev/env-name-patch.json
  common/ingress/kustomize/overlays/dev/kustomization.yaml
  common/ingress/kustomize/overlays/staging/env-name-patch.json
  common/ingress/kustomize/overlays/staging/kustomization.yaml
  microservices/client/kustomize/base/client-deployment.yaml
  microservices/client/kustomize/overlays/dev/kustomization.yaml
  microservices/client/kustomize/overlays/staging/kustomization.yaml
  microservices/client/src/containers/ServerPing.tsx
  microservices/server/kustomize/base/server-deployment.yaml
  microservices/server/kustomize/overlays/dev/config.properties
  microservices/server/kustomize/overlays/dev/kustomization.yaml
  microservices/server/kustomize/overlays/staging/config.properties
  microservices/server/kustomize/overlays/staging/kustomization.yaml
  skaffold.yaml
Labels: enhancement, client, database, server, ci/cd
